import { Container } from '@/components/shared/Container';
import Header from '@/components/shared/Header';

export const metadata = {
  title: 'Next Pizza | Корзина',
  description: 'Generated by Next.js',
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Header isHasSearch={false} isHasCart={false} className="border-gray-200" />
        {children}
      </Container>
    </div>
  );
}
