import { Container } from "@/components/shared/Container";
import Header from "@/components/shared/Header";
import { Suspense } from "react";

export const metadata = {
  title: "Next Pizza | Корзина",
  description: "Generated by Next.js",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Suspense>
          <Header isHasSearch={false} isHasCart={false} />
        </Suspense>
        {children}
      </Container>
    </div>
  );
}
