import type { Metadata } from 'next';
import toast, { Toaster } from 'react-hot-toast';
import { Suspense } from 'react';
import Header from '@/components/shared/Header';

export const metadata: Metadata = {
  title: 'Next Pizza | Главная',
  description: 'Generated by create next app',
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      <Suspense>
        <Header />
      </Suspense>
      {children}
      {modal}
    </main>
  );
}
