import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import toast, { Toaster } from 'react-hot-toast';

import './globals.css';

const nunito = Nunito({
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
});

// В главном layout не должно быть metadata и мы их удаляем и от главного layout отталкиваются другие layout 
// export const metadata: Metadata = {
//   title: 'Next Pizza | Главная',
//   description: 'Generated by create next app',
// };

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
        <head>
        <link data-rh="true" rel="icon" href="/logo.png" />
        </head>
      <body className={`${nunito.variable}  antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
